#!/usr/bin/env bash

args=('--force')

while read -r line; do
	if [[ "$line" == 'usr/lib/modules/'+([^/])'/pkgbase' ]]; then
		read -r pkgbase < "/${line}"
		kver="${line#'usr/lib/modules/'}"
		kver="${kver%'/pkgbase'}"
		echo "--> Building UKI for ${pkgbase} (${kver})"
		dracut "${args[@]}" --uefi "/efi/EFI/Linux/arch-${pkgbase}.efi" --kver "$kver"
	fi
done
