# Essential exports for config functionality
export ZSH=$HOME/.zsh
export UNIX_CONFIG_DIR=$(<$HOME/.unix_config_dir)


zstyle :compinstall filename "$HOME/.zshrc"
autoload -Uz compinit

ZSH_THEME="greg"
DISABLE_AUTO_TITLE="true"
COMPLETION_WAITING_DOTS="true"
DISABLE_UNTRACKED_FILES_DIRTY="true" # Disables listing untracked files as dirty saving recources
HIST_STAMPS="mm.dd.yyyy"
plugins=(themes zsh-syntax-highlighting git)

source $ZSH/oh-my-zsh.sh
source $ZSH/public_aliases.zsh

HISTFILE=~/.histfile
HISTSIZE=1000000
SAVEHIST=1000000
setopt appendhistory autocd extendedglob nomatch notify
unsetopt beep

bindkey -v # vi-style input
export KEYTIMEOUT=1 # kills vi mode lag

export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/texbin:$HOME/bin:$PATH

if type archey >/dev/null 2>&1; then
    archey
fi

