# Essential exports for config functionality
source /etc/profile
export ZSH=$HOME/.zsh
export UNIX_CONFIG_DIR=$HOME/.unix_config_dir


zstyle :compinstall filename "$HOME/.zshrc"
autoload -Uz compinit

ZSH_THEME="anon"
DISABLE_AUTO_TITLE="true"
COMPLETION_WAITING_DOTS="true"
DISABLE_UNTRACKED_FILES_DIRTY="true" # Disables listing untracked files as dirty saving recources
HIST_STAMPS="mm.dd.yyyy"
plugins=(vi-mode themes zsh-syntax-highlighting)

# OMZ
source $ZSH/oh-my-zsh.sh

HISTFILE=~/.histfile
HISTSIZE=1000000
SAVEHIST=1000000
setopt appendhistory autocd extendedglob nomatch notify
unsetopt beep

bindkey -v # vi-style input
export KEYTIMEOUT=1 # kills vi mode lag

# shh-agent
if hash keychain 2>/dev/null && [ $USER != "root" ]; then
	eval `keychain --lockwait 0 --eval --agents ssh id_rsa`
fi

if hash neofetch 2>/dev/null || type "neofetch" >/dev/null 2>&1; then
    neofetch
fi
# set vim as editor for everything ever
export VISUAL=vim
export EDITOR="$VISUAL"

export PATH=$PATH:$HOME/bin

# Scripting Language Version Managers

KERNAL=`uname`
if [[ $KERNAL == "Darwin" ]]; then
    # for homebrew and local executables
    export PATH=/usr/local/bin:$PATH:~/bin
fi

# Ruby version manager
export PATH=$HOME/.rbenv/bin:$PATH
test -s "$HOME/.rbenv/bin/rbenv" && eval "$(rbenv init -)"

# Elixir version manager
test -s "$HOME/.kiex/scripts/kiex" && source "$HOME/.kiex/scripts/kiex"

# NodeJS version manager
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

alias vi=vim

PSSAVE=$PS1

