execute pathogen#infect()
filetype off
syntax on
filetype plugin indent on
set sessionoptions-=options

" vim not vi
set nocompatible

filetype plugin indent on    " required

syntax on
set number

color monokai
color molokai

" Auto indent
set ai
" Smart indent
set si

" Treats tabs like buffers ... questionable
tab sball

" Allow backspacing over autoindent, line breaks and start of insert action
set backspace=indent,eol,start

" This shows what you are typing as a command. 
set showcmd

" Use visual bell instead of beeping when doing something wrong
set visualbell

" Show matching brackets when text indicator is over them
set showmatch 

" How many tenths of a second to blink when matching brackets
set mat=1

" And reset the terminal code for the visual bell. If visualbell is set, and
" this line is also included, vim will neither flash nor beep. If visualbell
" is unset, this does nothing.
set t_vb=

" Visualize tabs
"syntax match Tab /\t/
hi Tab gui=underline guifg=blue ctermbg=blue

" Use spaces instead of tabs
set expandtab

set ts=4
set softtabstop=0 noexpandtab
set sw=4

" Be smart when using tabs ;)
set smarttab

" default character width 100
set tw=120
set colorcolumn=120
set cursorline
set ruler
set wrap

" Hide the mouse pointer while typing
set mousehide

" Make the command-line completion better
set wildmenu

" Zee greatest shell
set shell=zsh

" TODO: the remaining language specific stuff should all be in submodules of plugin forks
autocmd BufRead,BufNewFile *.c,*.h set tw=80 colorcolumn=80 cindent
" makefiles need tabs 
autocmd FileType make setlocal noexpandtab
" MASM
autocmd BufRead,BufNewFile *.asm set ft=masm
" Obj-C++
autocmd BufRead,BufNewFile *.mm,*.mpp set tw=120 colorcolumn=80 cindent ft=objc++
" Ruby
autocmd FileType ruby setlocal expandtab tabstop=2 sw=2
autocmd FileType eruby setlocal expandtab tabstop=2 sw=2
" JS
autocmd FileType javascript setlocal expandtab tabstop=2 sw=2
let g:jsx_ext_required = 0

" C++ specific settings

let g:cpp_class_scope_highlight = 1
let g:cpp_member_variable_highlight = 1
let g:cpp_experimental_template_highlight = 1

" default gui settings
if has("gui_running")
    if has("gui_gtk2")
       set guifont=Consolas\ 14
    elseif has("gui_macvim")
       set guifont=Consolas:h16
    elseif has("gui_win32")
        set guifont=Consolas:h16:cANSI
    endif 
endif

" With a map leader it's possible to do extra key combinations
" like <leader>w saves the current file
let mapleader = ","
let g:mapleader = ","

"" Let powerline appear in non-split buffers (hack)
set laststatus=2

" Pressing ,ss will toggle and untoggle spell checking
map <leader>ss :setlocal spell!<cr>

" Toggle NERDTree with ctrl+n
map <C-n> :NERDTreeToggle<CR>
" Close NERDTree if it's the only open tab
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif
" Start NERDTree in current root dir
let g:NERDTreeChDirMode=2


" Syntastic
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 1
let g:syntastic_javascript_checkers = ['eslint']

let g:EclimCompletionMethod = 'omnifunc'
