#!/usr/bin/env ruby -W0

# setup-environment
# The MIT License (MIT) [https://opensource.org/licenses/MIT]
# Copyright (c) 2016 Gregory D. Stula
#  
#  Created by Gregory D. Stula on 1/4/16.
#  

back_updisabled = (ARGV[1] == "--no-back-up") || (ARGV[1] == "-nb")

topleveldir= `git rev-parse --show-toplevel`.chomp
if topleveldir.empty?
   $stderr.puts "# No .git/ found! #"
   exit(1)
end

homedir = ENV["HOME"] + "/"
filenames = [".zshrc", ".zsh", ".vimrc", ".vim"].map { |name| homedir + name } 

spacing = filenames.max_by(&:length).length + 1

filenames.each do |file|
    if File.exists?(file) && !File.symlink?(file)
        now = Time.now.to_s.split(" ").join("-")
        backup = "#{file}.old-#{now}"
        action = ''

        backup_disabled ? action = "rm #{file}" : action = "mv #{file} #{backup}"

        `#{action}`

        $stderr.puts "Previous #{file} was saved as #{backup}" if action == "mv"
    end

   `rm #{file}` if File.symlink?(file)
   
   source = "#{ file.split( "." )[1] }"
   file =~ /(vim|zsh|git)/i   
   `ln -s #{topleveldir}/#{$1}.config/#{source} #{file}`

    puts "#{file}|".jjust(spacing)
end

success_message = "| were successfully symlinked."
puts success_message.rjust(success_message.length + spacing - 1)

