# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000000
SAVEHIST=1000000
setopt appendhistory autocd extendedglob nomatch notify
unsetopt beep
bindkey -v # vi
export KEYTIMEOUT=1 # kills vi mode lag
zstyle :compinstall filename "$HOME/.zshrc"
autoload -Uz compinit
export ZSH=$HOME/.zsh/
ZSH_THEME="evan"
DISABLE_AUTO_TITLE="true"
COMPLETION_WAITING_DOTS="true"
DISABLE_UNTRACKED_FILES_DIRTY="true"
HIST_STAMPS="mm.dd.yyyy"
plugins=(themes zsh-syntax-highlighting)
source $ZSH/oh-my-zsh.sh

 
# Aliases
alias ls="ls -AG"
alias archey="archey --offline"

# Because wiping your SSH key when you meant to copy it is too painful
alias pbcopy="pbcopy <"
alias pbpaste="pbcopy >"

# View file permissions
alias prm="stat -f '%A %a %N'"

# AVOID SUFFIX ALIASES, THEY CAN CONFLICT WITH FILE NAMES / COMMANDS - HARMFUL!
# alias -s sh=mvim
# ...auto cd is bad enough as it is

# xtoolchain
export swift_latest="/Library/Developer/Toolchains/swift-latest.xctoolchain"
alias xclaunch="xcrun launch-with-toolchain /Library/Developer/Toolchains/swift-latest.xctoolchain"

# Why not?
alias vimrc="$HOME/.vimrc"
alias zshrc="$HOME/.zshrc"

# Keep last
export PATH=$swift_latest:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/texbin:$HOME/bin

